# Generated by Django 4.0.6 on 2022-09-06 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0002_alter_task_createddate_alter_task_modifieddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='GUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
