# Generated by Django 4.0.6 on 2022-09-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0003_task_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskID', models.IntegerField(null=True)),
                ('GUID', models.UUIDField()),
                ('JSONData', models.JSONField(null=True)),
                ('CreatedDate', models.DateTimeField(null=True)),
                ('CreatedBy', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='CurrentIteration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='TaskID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='IsEmon',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='TotalIterations',
            field=models.IntegerField(default=2),
        ),
    ]
